IW21:
  "SAPLIQS0|0100":
    "Tipo de nota": 'wnd[0]/usr/ctxtRIWO00-QMART'
    "Nota": 'wnd[0]/usr/ctxtRIWO00-QMNUM'
    "Nº modelo nota": 'wnd[0]/usr/ctxtRIWO00-QWRNUM'
  "SAPLIQS0|7200":
    "Texto Breve": 'wnd[0]/usr/subSCREEN_1:SAPLIQS0:1050/subNOTIF_TYPE:SAPLIQS0:1051/txtVIQMEL-QMTXT'
    "Local de instalação": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_1:SAPLIQS0:7322/subOBJEKT:SAPLIWO1:0100/ctxtRIWO1-TPLNR'
    "Notificador": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_3:SAPLIQS0:7326/ctxtVIQMEL-QMNAM'
    "Prioridade": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_4:SAPLIQS0:7330/cmbVIQMEL-PRIOK'
    "Ramal": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_5:SAPLIQS0:7900/ssubUSER0001:SAPLXQQM:0103/txtQMEL-ZZNR_RAMAL'

IW31:
  "SAPLCOIH|0100":
    "Tipo de ordem": 'wnd[0]/usr/ctxtAUFPAR-PM_AUFART'
    "Local de instalação": 'wnd[0]/usr/subOBJECT:SAPLCOIH:7100/ctxtCAUFVD-TPLNR'
    "Nº equipamento": 'wnd[0]/usr/subOBJECT:SAPLCOIH:7100/ctxtCAUFVD-EQUNR'

  "SAPLCOIH|3000":
    "Texto Breve": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/subSUB_KOPF:SAPLCOIH:1102/txtCAUFVD-KTEXT'
    "Tipo de atividade de manutenção": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subHEADER:SAPLCOIH:0154/ctxtCAUFVD-ILART'
    "Prioridade": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subTERM:SAPLCOIH:7300/cmbCAUFVD-PRIOK'
    
    "Criar Nota": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subHEADER:SAPLCOIH:0154/btnICON_NTF'
    
    "Aba Operações": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpVGUE'
    "Texto Operação": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-LTXA1[7,0]'
    "Trabalho": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,0]'
    "Nº colaboradores": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,0]'
  
    "Texto Operação 2": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-LTXA1[7,1]'
    "Trabalho 2": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,1]'
    "Nº colaboradores 2": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,1]'

    "Texto Operação 3": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-LTXA1[7,2]'
    "Trabalho 3": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,2]'
    "Nº colaboradores 3": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,2]'

  "SAPLIQS0|7200":
    "Notificador": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_3:SAPLIQS0:7326/ctxtVIQMEL-QMNAM'
    "Prioridade da Nota": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_4:SAPLIQS0:7330/cmbVIQMEL-PRIOK'
    "Ramal": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_5:SAPLIQS0:7900/ssubUSER0001:SAPLXQQM:0103/txtQMEL-ZZNR_RAMAL'

IW34:
  "SAPLCOIH|0100":
    "Tipo de ordem": 'wnd[0]/usr/ctxtAUFPAR-PM_AUFART'
    "Nota": 'wnd[0]/usr/ctxtAUFPAR-QMNUM'
  "SAPLCOIH|3000":
    "Texto Breve": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/subSUB_KOPF:SAPLCOIH:1102/txtCAUFVD-KTEXT'
    "Tipo de atividade de manutenção": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subHEADER:SAPLCOIH:0154/ctxtCAUFVD-ILART'
    "Prioridade": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subTERM:SAPLCOIH:7300/cmbCAUFVD-PRIOK'
    "Aba Operações": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpVGUE'
    "Trabalho": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,0]'
    "Nº colaboradores": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,0]'

IW32:
  "SAPLCOIH|0100":
    "Ordem": 'wnd[0]/usr/ctxtCAUFVD-AUFNR'
    "Imprimir": 'wnd[0]/tbar[1]/btn[25]'
    "Documentação ordem 2080": 'wnd[0]/tbar[0]/btn[86]'
    "Selecionar documentação 2080": 'wnd[1]/usr/tblSAPLIPRTTC_WORKPAPERS/txtWWORKPAPER-WORKPAPER[0,8]'
    "Visualização de impressão": 'wnd[1]/tbar[0]/btn[16]'

IW41:
  "SAPLCORU|0100":
    "Ordem": 'wnd[0]/usr/ctxtCORUF-AUFNR'

IP41:
  "SAPLIWP3|0100":
    "Plano manutenção": 'wnd[0]/usr/txtRMIPM-WARPL'
    "Ctg.plano manut.": 'wnd[0]/usr/cmbRMIPM-MPTYP'

IP42:
  "SAPLIWP3|0100":
    "Plano manutenção": 'wnd[0]/usr/txtRMIPM-WARPL'
    "Ctg.plano manut.": 'wnd[0]/usr/cmbRMIPM-MPTYP'
    "Estratégia": 'wnd[0]/usr/ctxtRMIPM-WSTRA'