IW21:
  metadata:
    btn_salvar: "wnd[0]/tbar[0]/btn[11]"
    btn_simular: "wnd[0]/tbar[1]/btn[7]" # Botão de verificar/simular
    regex_sucesso: '(?:Nota|Aviso)\s+(\d+)' # Regex para extrair o número
  
  "SAPLIQS0|0100":
    "Tipo de nota": 'wnd[0]/usr/ctxtRIWO00-QMART'
    "Nota": 'wnd[0]/usr/ctxtRIWO00-QMNUM'
    "Nº modelo nota": 'wnd[0]/usr/ctxtRIWO00-QWRNUM'

  "SAPLIQS0|7200":
    "Texto Breve": 'wnd[0]/usr/subSCREEN_1:SAPLIQS0:1050/subNOTIF_TYPE:SAPLIQS0:1051/txtVIQMEL-QMTXT'
    "Local de instalação": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_1:SAPLIQS0:7322/subOBJEKT:SAPLIWO1:0100/ctxtRIWO1-TPLNR'
    "Notificador": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_3:SAPLIQS0:7326/ctxtVIQMEL-QMNAM'
    "Prioridade": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_4:SAPLIQS0:7330/cmbVIQMEL-PRIOK'
    "Ramal": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_5:SAPLIQS0:7900/ssubUSER0001:SAPLXQQM:0103/txtQMEL-ZZNR_RAMAL'

IW31:
  "SAPLCOIH|0100":
    "Tipo de ordem": 'wnd[0]/usr/ctxtAUFPAR-PM_AUFART'
    "Local de instalação": 'wnd[0]/usr/subOBJECT:SAPLCOIH:7100/ctxtCAUFVD-TPLNR'
    "Nº equipamento": 'wnd[0]/usr/subOBJECT:SAPLCOIH:7100/ctxtCAUFVD-EQUNR'

  "SAPLCOIH|3000":
    "Texto Breve": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/subSUB_KOPF:SAPLCOIH:1102/txtCAUFVD-KTEXT'
    "Tipo de atividade de manutenção": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subHEADER:SAPLCOIH:0154/ctxtCAUFVD-ILART'
    "Prioridade": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subTERM:SAPLCOIH:7300/cmbCAUFVD-PRIOK'
    
    "Criar Nota": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subHEADER:SAPLCOIH:0154/btnICON_NTF'
    
    "Aba Operações": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpVGUE'
    "Texto Operação": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-LTXA1[7,0]'
    "Trabalho": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,0]'
    "Nº colaboradores": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,0]'
  
    "Texto Operação 2": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-LTXA1[7,1]'
    "Trabalho 2": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,1]'
    "Nº colaboradores 2": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,1]'

    "Texto Operação 3": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-LTXA1[7,2]'
    "Trabalho 3": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,2]'
    "Nº colaboradores 3": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,2]'

  "SAPLIQS0|7200":
    "Notificador": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_3:SAPLIQS0:7326/ctxtVIQMEL-QMNAM'
    "Prioridade da Nota": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_4:SAPLIQS0:7330/cmbVIQMEL-PRIOK'
    "Ramal": 'wnd[0]/usr/tabsTAB_GROUP_10/tabp10\TAB01/ssubSUB_GROUP_10:SAPLIQS0:7235/subCUSTOM_SCREEN:SAPLIQS0:7212/subSUBSCREEN_5:SAPLIQS0:7900/ssubUSER0001:SAPLXQQM:0103/txtQMEL-ZZNR_RAMAL'

IW34:
  "SAPLCOIH|0100":
    "Tipo de ordem": 'wnd[0]/usr/ctxtAUFPAR-PM_AUFART'
    "Nota": 'wnd[0]/usr/ctxtAUFPAR-QMNUM'
    
  "SAPLCOIH|3000":
    "Texto Breve": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/subSUB_KOPF:SAPLCOIH:1102/txtCAUFVD-KTEXT'
    "Tipo de atividade de manutenção": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subHEADER:SAPLCOIH:0154/ctxtCAUFVD-ILART'
    "Prioridade": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpIHKZ/ssubSUB_AUFTRAG:SAPLCOIH:1120/subTERM:SAPLCOIH:7300/cmbCAUFVD-PRIOK'
    "Aba Operações": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1100/tabsTS_1100/tabpVGUE'
    "Trabalho": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ARBEI[10,0]'
    "Nº colaboradores": 'wnd[0]/usr/subSUB_ALL:SAPLCOIH:3001/ssubSUB_LEVEL:SAPLCOIH:1107/tabsTS_1100/tabpVGUE/ssubSUB_AUFTRAG:SAPLCOVG:3010/tblSAPLCOVGTCTRL_3010/txtAFVGD-ANZZL[12,0]'

IW32:
  "SAPLCOIH|0100":
    "Ordem": 'wnd[0]/usr/ctxtCAUFVD-AUFNR'
    
IW41:
  "SAPLCORU|0100":
    "Ordem": 'wnd[0]/usr/ctxtCORUF-AUFNR'
    "Nº pessoal": 'wnd[0]/usr/ctxtAFRUD-PERNR'
    "Conf.final": 'wnd[0]/usr/chkAFRUD-AUERU'
    "Dar baixa res.": 'wnd[0]/usr/chkAFRUD-AUSOR'
    "Início trabalho data": 'wnd[0]/usr/ctxtAFRUD-ISDD'
    "Início trabalho hora": 'wnd[0]/usr/ctxtAFRUD-ISDZ'
    "Fim trabalho data": 'wnd[0]/usr/ctxtAFRUD-IEDD'
    "Fim trabalho hora": 'wnd[0]/usr/ctxtAFRUD-IEDZ'
    "Tabela confirmações": 'wnd[0]/usr/tblSAPLCORUTC_3100'

IP41:
  "SAPLIWP3|0100":
    "Ctg.plano de manutenção": "wnd[0]/usr/cmbRMIPM-MPTYP"

  "SAPLIWP3|6000":
    "Texto do plano de manutenção": "wnd[0]/usr/subSUBSCREEN_HEAD:SAPLIWP3:6000/txtRMIPM-WPTXT"

  "SAPLIWP3|0205":
    "Ciclo": "wnd[0]/usr/subSUBSCREEN_MPLAN:SAPLIWP3:8001/tabsTABSTRIP_HEAD/tabpT\\01/ssubSUBSCREEN_BODY1:SAPLIWP3:8011/subSUBSCREEN_CYCLE:SAPLIWP3:0205/txtRMIPM-ZYKL1"
    "Unidade do ciclo": "wnd[0]/usr/subSUBSCREEN_MPLAN:SAPLIWP3:8001/tabsTABSTRIP_HEAD/tabpT\\01/ssubSUBSCREEN_BODY1:SAPLIWP3:8011/subSUBSCREEN_CYCLE:SAPLIWP3:0205/ctxtRMIPM-ZEIEH"

  "SAPLIWO1|0100":
    "Local de instalação": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_1:SAPLIWO1:0100/ctxtRIWO1-TPLNR"
    "Nº equipamento": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_1:SAPLIWO1:0100/ctxtRIWO1-EQUNR"

  "SAPLIWP3|0500":
    "Tipo de ordem": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/ctxtRMIPM-AUART"
    "Tipo de atividade de manutenção": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/ctxtRMIPM-ILART"
    "Prioridade": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/cmbRMIPM-PRIOK"

  "SAPLIWP3|0113":
    "Campo Ordenação": "wnd[0]/usr/subSUBSCREEN_MPLAN:SAPLIWP3:8001/tabsTABSTRIP_HEAD/tabpT\\03/ssubSUBSCREEN_BODY1:SAPLIWP3:8012/subSUBSCREEN_PARAMETER:SAPLIWP3:0113/cmbRMIPM-PLAN_SORT"

  "SAPLIWP3|8022":
    "Criar lista de tarefas": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/btnARBEITSPLAN_1"

  "SAPLCPDI|1000":
    "Utilização": "wnd[0]/usr/ctxtPLKOD-VERWE"
    "Grupo de planejamento": "wnd[0]/usr/ctxtPLKOD-VAGRP"
    "Status do plano": "wnd[0]/usr/ctxtPLKOD-STATU"

  "SAPLCPDI|3400":
    "Descrição da operação": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/txtPLPOD-LTXA1[5,0]"
    "Trabalho": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/txtPLPOD-ARBEI[7,0]"
    "Unidade trabalho": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/ctxtPLPOD-ARBEH[8,0]"
    "Duração": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/txtPLPOD-DAUNO[10,0]"
    "Unidade duração": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/ctxtPLPOD-DAUNE[11,0]"

IP42:
  "SAPLIWP3|0100":
    "Ctg.plano manut.": "wnd[0]/usr/cmbRMIPM-MPTYP"
    "Estratégia": "wnd[0]/usr/ctxtRMIPM-WSTRA"

  "SAPLIWP3|6000":
    "Texto do plano de manutenção": "wnd[0]/usr/subSUBSCREEN_HEAD:SAPLIWP3:6000/txtRMIPM-WPTXT"

  "SAPLIWP3|0207":
    "Ciclo": "wnd[0]/usr/subSUBSCREEN_MPLAN:SAPLIWP3:8001/tabsTABSTRIP_HEAD/tabpT\\01/ssubSUBSCREEN_BODY1:SAPLIWP3:8011/subSUBSCREEN_CYCLE:SAPLIWP3:0207/txtRMIPM-ZYKL1"
    "Unidade do ciclo": "wnd[0]/usr/subSUBSCREEN_MPLAN:SAPLIWP3:8001/tabsTABSTRIP_HEAD/tabpT\\01/ssubSUBSCREEN_BODY1:SAPLIWP3:8011/subSUBSCREEN_CYCLE:SAPLIWP3:0207/ctxtRMIPM-ZEIEH"

  "SAPLIWO1|0100":
    "Local de instalação": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_1:SAPLIWO1:0100/ctxtRIWO1-TPLNR"
    "Nº equipamento": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_1:SAPLIWO1:0100/ctxtRIWO1-EQUNR"

  "SAPLIWP3|0500":
    "Tipo de ordem": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/ctxtRMIPM-AUART"
    "Tipo de atividade de manutenção": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/ctxtRMIPM-ILART"
    "Prioridade": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/cmbRMIPM-PRIOK"
    
  "SAPLIWP3|8022": 
    "Criar lista de tarefas": "wnd[0]/usr/subSUBSCREEN_MITEM:SAPLIWP3:8002/tabsTABSTRIP_ITEM/tabpT\\11/ssubSUBSCREEN_BODY2:SAPLIWP3:8022/subSUBSCREEN_ITEM_2:SAPLIWP3:0500/btnARBEITSPLAN_1"

  "SAPLIWP3|0113":
    "Campo Ordenação": "wnd[0]/usr/subSUBSCREEN_MPLAN:SAPLIWP3:8001/tabsTABSTRIP_HEAD/tabpT\\03/ssubSUBSCREEN_BODY1:SAPLIWP3:8012/subSUBSCREEN_PARAMETER:SAPLIWP3:0113/cmbRMIPM-PLAN_SORT"

  "SAPLCPDI|1000":
    "Utilização": "wnd[0]/usr/ctxtPLKOD-VERWE"
    "Grupo de planejamento": "wnd[0]/usr/ctxtPLKOD-VAGRP"
    "Status do plano": "wnd[0]/usr/ctxtPLKOD-STATU"

  "SAPLCPDI|3400":
    "Descrição da operação": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/txtPLPOD-LTXA1[5,0]"
    "Trabalho": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/txtPLPOD-ARBEI[7,0]"
    "Unidade trabalho": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/ctxtPLPOD-ARBEH[8,0]"
    "Duração": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/txtPLPOD-DAUNO[10,0]"
    "Unidade duração": "wnd[0]/usr/tblSAPLCPDITCTRL_3400/ctxtPLPOD-DAUNE[11,0]"

CO01:
  metadata:
    btn_salvar: "wnd[0]/tbar[0]/btn[11]"
  "SAPLCOKO1|0100":
    "Material": "wnd[0]/usr/ctxtRC27M-MATNR"
    "Centro de produção": "wnd[0]/usr/ctxtRC27M-WERKS"
    "Tipo de ordem": "wnd[0]/usr/ctxtRC27M-AUART"
  "SAPLCOKO1|0110":
    "Qtd.total": "wnd[0]/usr/txtCAUFVD-GAMNG"
    "Inicio": "wnd[0]/usr/ctxtCAUFVD-GSTRP"
    "Tipo": "wnd[0]/usr/cmbCAUFVD-TERKZ"

CO02:
  metadata:
    btn_salvar: "wnd[0]/tbar[0]/btn[11]"
  "SAPLCOKO1|0100":
    "Ordem": "wnd[0]/usr/ctxtCAUFVD-AUFNR"
  "SAPLCOKO1|0110":
    "Inicio": "wnd[0]/usr/ctxtCAUFVD-GSTRP"
    "Fim": "wnd[0]/usr/ctxtCAUFVD-GLTRP"
    "Liberar": "wnd[0]/tbar[1]/btn[23]"
    "Imprimir spool": "wnd[0]/tbar[1]/btn[86]"
    "Menu Funções": "wnd[0]/mbar/menu[3]"
    "Menu Limitar processamento": "wnd[0]/mbar/menu[3]/menu[8]"
    "Menu Concluir tecnicamente": "wnd[0]/mbar/menu[3]/menu[8]/menu[0]"

CO11N:
  metadata:
    btn_salvar: "wnd[0]/tbar[0]/btn[11]"
  "SAPLCORU|1000":
    "Ordem": "wnd[0]/usr/ctxtAFRUD-AUFNR"
    "Operação": "wnd[0]/usr/ctxtAFRUD-VORNR"
    "Ajuda operação": "wnd[0]/usr/btn%#AUTOTEXT001"
    "Tabela operações popup": "wnd[1]/usr/tblSAPLCORUT"

CO07:
  metadata:
    btn_salvar: "wnd[0]/tbar[0]/btn[11]"
  "SAPLCOKO1|0100":
    "Centro": "wnd[0]/usr/ctxtCAUFVD-WERKS"
    "Tipo de ordem": "wnd[0]/usr/ctxtCAUFVD-AUART"
  "SAPLCOKO1|0110":
    "Texto breve": "wnd[0]/usr/txtCAUFVD-KTEXT"
    "Qtd.total": "wnd[0]/usr/txtCAUFVD-GAMNG"
    "Unidade": "wnd[0]/usr/ctxtCAUFVD-GMEIN"
    "Tipo": "wnd[0]/usr/cmbCAUFVD-TERKZ"
    "Aba Atribuição": "wnd[0]/usr/tabsTABSTRIP/tabpZUOR"
    "Centro de lucro": "wnd[0]/usr/ctxtCAUFVD-PRCTR"
